### ISSUE TITLE
Problem with multiple button presses and analogue.

### ISSUE THREAD

**Issue by m0vse** [lebaston100/GVG110panelMod#2]
Hi. I am currently adapting a GVG100 panel, I have made all of the modifications in your Wiki, my panel only has a single 7805 regulator though but other than that, all component values and positions appear to be the same.

I have found that if I press more than 1 button at a time, I get very strange results with it appearing to select many other buttons in a random way. Have you seen this before?

Also I have found that the analogue seems to be very erratic. I have tried cleaning the potentiometers but not sure how sealed they are, I see that you are sampling twice so I assume you had similar issues?

Thanks

Phil

**Comment by lebaston100** [comment]
Hi.
No, i have not see that. In theory every button will be read individually.
The analog on mine worked pretty fine. I just do the sampling multiple times just to stabilize the values a bit more just because it's analog.
Also i have not played with it since this project was released so i'm not up to date on the technical details.

**Comment by m0vse** [comment]
Hi, I have managed to diagnose the analogue a bit better. It looks like sometimes I am getting 512 more than the actual reading so it appears that bit 10 is "intermittent". I suspect that this may be a timing issue but I can do a bit of a 'hack' to fix this by just ignoring the status of the 10th bit if it is different to the last reading I guess? Not an ideal fix and if it is a fault on the DAC1001, this could be difficult(expensive) to replace as it is an obsolete part.

**Comment by lebaston100** [comment]
Interesting. This is too far back to remember anything. But i think i kept an eye on the timings from the datasheet.
I just know that the code as it is works fine for my panel and someone else who currently is using it without any problems.
But the arduino code is mostly just a template as how to interface with it, you can play with the timings, add handling for that stuff if you want.

**Comment by lebaston100** [comment]
I'll close for now, feel free to continue the discussion here.
